Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Command\\GuildListCommand",
            "name": "GuildListCommand",
            "summary": "",
            "url": "classes/App-Command-GuildListCommand.html"
        },                {
            "fqsen": "\\App\\Command\\GuildListCommand\u003A\u003AsetUserRepository\u0028\u0029",
            "name": "setUserRepository",
            "summary": "",
            "url": "classes/App-Command-GuildListCommand.html#method_setUserRepository"
        },                {
            "fqsen": "\\App\\Command\\GuildListCommand\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "",
            "url": "classes/App-Command-GuildListCommand.html#method_execute"
        },                {
            "fqsen": "\\App\\Command\\GuildListCommand\u003A\u003A\u0024guildRepository",
            "name": "guildRepository",
            "summary": "",
            "url": "classes/App-Command-GuildListCommand.html#property_guildRepository"
        },                {
            "fqsen": "\\App\\Command\\UserDemoteCommand",
            "name": "UserDemoteCommand",
            "summary": "",
            "url": "classes/App-Command-UserDemoteCommand.html"
        },                {
            "fqsen": "\\App\\Command\\UserDemoteCommand\u003A\u003Aconfigure\u0028\u0029",
            "name": "configure",
            "summary": "",
            "url": "classes/App-Command-UserDemoteCommand.html#method_configure"
        },                {
            "fqsen": "\\App\\Command\\UserDemoteCommand\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "",
            "url": "classes/App-Command-UserDemoteCommand.html#method_execute"
        },                {
            "fqsen": "\\App\\Command\\UserListCommand",
            "name": "UserListCommand",
            "summary": "",
            "url": "classes/App-Command-UserListCommand.html"
        },                {
            "fqsen": "\\App\\Command\\UserListCommand\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "",
            "url": "classes/App-Command-UserListCommand.html#method_execute"
        },                {
            "fqsen": "\\App\\Command\\UserPromoteCommand",
            "name": "UserPromoteCommand",
            "summary": "",
            "url": "classes/App-Command-UserPromoteCommand.html"
        },                {
            "fqsen": "\\App\\Command\\UserPromoteCommand\u003A\u003Aconfigure\u0028\u0029",
            "name": "configure",
            "summary": "",
            "url": "classes/App-Command-UserPromoteCommand.html#method_configure"
        },                {
            "fqsen": "\\App\\Command\\UserPromoteCommand\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "",
            "url": "classes/App-Command-UserPromoteCommand.html#method_execute"
        },                {
            "fqsen": "\\App\\Console\\Command",
            "name": "Command",
            "summary": "",
            "url": "classes/App-Console-Command.html"
        },                {
            "fqsen": "\\App\\Console\\Command\u003A\u003AsetDefinitionListConverter\u0028\u0029",
            "name": "setDefinitionListConverter",
            "summary": "",
            "url": "classes/App-Console-Command.html#method_setDefinitionListConverter"
        },                {
            "fqsen": "\\App\\Console\\Command\u003A\u003Ainitialize\u0028\u0029",
            "name": "initialize",
            "summary": "",
            "url": "classes/App-Console-Command.html#method_initialize"
        },                {
            "fqsen": "\\App\\Console\\Command\u003A\u003ASUCCESS",
            "name": "SUCCESS",
            "summary": "",
            "url": "classes/App-Console-Command.html#constant_SUCCESS"
        },                {
            "fqsen": "\\App\\Console\\Command\u003A\u003AFAILURE",
            "name": "FAILURE",
            "summary": "",
            "url": "classes/App-Console-Command.html#constant_FAILURE"
        },                {
            "fqsen": "\\App\\Console\\Command\u003A\u003AINVALID",
            "name": "INVALID",
            "summary": "",
            "url": "classes/App-Console-Command.html#constant_INVALID"
        },                {
            "fqsen": "\\App\\Console\\Command\u003A\u003A\u0024io",
            "name": "io",
            "summary": "",
            "url": "classes/App-Console-Command.html#property_io"
        },                {
            "fqsen": "\\App\\Console\\Command\u003A\u003A\u0024definitionListConverter",
            "name": "definitionListConverter",
            "summary": "",
            "url": "classes/App-Console-Command.html#property_definitionListConverter"
        },                {
            "fqsen": "\\App\\Console\\Style\\DefinitionListConverter",
            "name": "DefinitionListConverter",
            "summary": "",
            "url": "classes/App-Console-Style-DefinitionListConverter.html"
        },                {
            "fqsen": "\\App\\Console\\Style\\DefinitionListConverter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Console-Style-DefinitionListConverter.html#method___construct"
        },                {
            "fqsen": "\\App\\Console\\Style\\DefinitionListConverter\u003A\u003Aconvert\u0028\u0029",
            "name": "convert",
            "summary": "",
            "url": "classes/App-Console-Style-DefinitionListConverter.html#method_convert"
        },                {
            "fqsen": "\\App\\Console\\Style\\DefinitionListConverter\u003A\u003Aflatten\u0028\u0029",
            "name": "flatten",
            "summary": "",
            "url": "classes/App-Console-Style-DefinitionListConverter.html#method_flatten"
        },                {
            "fqsen": "\\App\\Console\\Style\\DefinitionListConverter\u003A\u003A\u0024normalizer",
            "name": "normalizer",
            "summary": "",
            "url": "classes/App-Console-Style-DefinitionListConverter.html#property_normalizer"
        },                {
            "fqsen": "\\App\\Console\\UserCommand",
            "name": "UserCommand",
            "summary": "",
            "url": "classes/App-Console-UserCommand.html"
        },                {
            "fqsen": "\\App\\Console\\UserCommand\u003A\u003AsetUserRepository\u0028\u0029",
            "name": "setUserRepository",
            "summary": "",
            "url": "classes/App-Console-UserCommand.html#method_setUserRepository"
        },                {
            "fqsen": "\\App\\Console\\UserCommand\u003A\u003AsetValidator\u0028\u0029",
            "name": "setValidator",
            "summary": "",
            "url": "classes/App-Console-UserCommand.html#method_setValidator"
        },                {
            "fqsen": "\\App\\Console\\UserCommand\u003A\u003AvalidateDiscordId\u0028\u0029",
            "name": "validateDiscordId",
            "summary": "",
            "url": "classes/App-Console-UserCommand.html#method_validateDiscordId"
        },                {
            "fqsen": "\\App\\Console\\UserCommand\u003A\u003AARGUMENT_NAME_DISCORD_ID",
            "name": "ARGUMENT_NAME_DISCORD_ID",
            "summary": "",
            "url": "classes/App-Console-UserCommand.html#constant_ARGUMENT_NAME_DISCORD_ID"
        },                {
            "fqsen": "\\App\\Console\\UserCommand\u003A\u003AARGUMENT_DESCRIPTION_DISCORD_ID",
            "name": "ARGUMENT_DESCRIPTION_DISCORD_ID",
            "summary": "",
            "url": "classes/App-Console-UserCommand.html#constant_ARGUMENT_DESCRIPTION_DISCORD_ID"
        },                {
            "fqsen": "\\App\\Console\\UserCommand\u003A\u003A\u0024userRepository",
            "name": "userRepository",
            "summary": "",
            "url": "classes/App-Console-UserCommand.html#property_userRepository"
        },                {
            "fqsen": "\\App\\Console\\UserCommand\u003A\u003A\u0024validator",
            "name": "validator",
            "summary": "",
            "url": "classes/App-Console-UserCommand.html#property_validator"
        },                {
            "fqsen": "\\App\\Controller\\DiscordController",
            "name": "DiscordController",
            "summary": "",
            "url": "classes/App-Controller-DiscordController.html"
        },                {
            "fqsen": "\\App\\Controller\\DiscordController\u003A\u003AwebhookEvent\u0028\u0029",
            "name": "webhookEvent",
            "summary": "",
            "url": "classes/App-Controller-DiscordController.html#method_webhookEvent"
        },                {
            "fqsen": "\\App\\Controller\\DiscordController\u003A\u003AWEBHOOK_EVENT_ROUTE_PATH",
            "name": "WEBHOOK_EVENT_ROUTE_PATH",
            "summary": "",
            "url": "classes/App-Controller-DiscordController.html#constant_WEBHOOK_EVENT_ROUTE_PATH"
        },                {
            "fqsen": "\\App\\Controller\\DiscordController\u003A\u003AWEBHOOK_EVENT_ROUTE_NAME",
            "name": "WEBHOOK_EVENT_ROUTE_NAME",
            "summary": "",
            "url": "classes/App-Controller-DiscordController.html#constant_WEBHOOK_EVENT_ROUTE_NAME"
        },                {
            "fqsen": "\\App\\DependencyInjection\\Parameters",
            "name": "Parameters",
            "summary": "",
            "url": "classes/App-DependencyInjection-Parameters.html"
        },                {
            "fqsen": "\\App\\DependencyInjection\\Parameters\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-DependencyInjection-Parameters.html#method___construct"
        },                {
            "fqsen": "\\App\\DependencyInjection\\Parameters\u003A\u003ADEFAULT_STRING_PARAMETER",
            "name": "DEFAULT_STRING_PARAMETER",
            "summary": "",
            "url": "classes/App-DependencyInjection-Parameters.html#constant_DEFAULT_STRING_PARAMETER"
        },                {
            "fqsen": "\\App\\DependencyInjection\\Parameters\u003A\u003ADISCORD_APP_PUBLIC_KEY",
            "name": "DISCORD_APP_PUBLIC_KEY",
            "summary": "",
            "url": "classes/App-DependencyInjection-Parameters.html#constant_DISCORD_APP_PUBLIC_KEY"
        },                {
            "fqsen": "\\App\\DependencyInjection\\Parameters\u003A\u003ADISCORD_OAUTH2_CLIENT_ID",
            "name": "DISCORD_OAUTH2_CLIENT_ID",
            "summary": "",
            "url": "classes/App-DependencyInjection-Parameters.html#constant_DISCORD_OAUTH2_CLIENT_ID"
        },                {
            "fqsen": "\\App\\DependencyInjection\\Parameters\u003A\u003ADISCORD_OAUTH2_CLIENT_SECRET",
            "name": "DISCORD_OAUTH2_CLIENT_SECRET",
            "summary": "",
            "url": "classes/App-DependencyInjection-Parameters.html#constant_DISCORD_OAUTH2_CLIENT_SECRET"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\ApplicationAuthorizedWebhookEventBody",
            "name": "ApplicationAuthorizedWebhookEventBody",
            "summary": "",
            "url": "classes/App-Dto-Discord-ApplicationAuthorizedWebhookEventBody.html"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\ApplicationAuthorizedWebhookEventBody\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Dto-Discord-ApplicationAuthorizedWebhookEventBody.html#method___construct"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\ApplicationAuthorizedWebhookEventBody\u003A\u003A\u0024data",
            "name": "data",
            "summary": "",
            "url": "classes/App-Dto-Discord-ApplicationAuthorizedWebhookEventBody.html#property_data"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\ApplicationAuthorizedWebhookEventData",
            "name": "ApplicationAuthorizedWebhookEventData",
            "summary": "",
            "url": "classes/App-Dto-Discord-ApplicationAuthorizedWebhookEventData.html"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\ApplicationAuthorizedWebhookEventData\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Dto-Discord-ApplicationAuthorizedWebhookEventData.html#method___construct"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\ApplicationAuthorizedWebhookEventData\u003A\u003A\u0024user",
            "name": "user",
            "summary": "",
            "url": "classes/App-Dto-Discord-ApplicationAuthorizedWebhookEventData.html#property_user"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\ApplicationAuthorizedWebhookEventData\u003A\u003A\u0024scopes",
            "name": "scopes",
            "summary": "",
            "url": "classes/App-Dto-Discord-ApplicationAuthorizedWebhookEventData.html#property_scopes"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\ApplicationAuthorizedWebhookEventData\u003A\u003A\u0024integration_type",
            "name": "integration_type",
            "summary": "",
            "url": "classes/App-Dto-Discord-ApplicationAuthorizedWebhookEventData.html#property_integration_type"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\ApplicationAuthorizedWebhookEventData\u003A\u003A\u0024guild",
            "name": "guild",
            "summary": "",
            "url": "classes/App-Dto-Discord-ApplicationAuthorizedWebhookEventData.html#property_guild"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\AvatarDecorationData",
            "name": "AvatarDecorationData",
            "summary": "",
            "url": "classes/App-Dto-Discord-AvatarDecorationData.html"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\AvatarDecorationData\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Dto-Discord-AvatarDecorationData.html#method___construct"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\AvatarDecorationData\u003A\u003A\u0024asset",
            "name": "asset",
            "summary": "",
            "url": "classes/App-Dto-Discord-AvatarDecorationData.html#property_asset"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\AvatarDecorationData\u003A\u003A\u0024sku_id",
            "name": "sku_id",
            "summary": "",
            "url": "classes/App-Dto-Discord-AvatarDecorationData.html#property_sku_id"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Emoji",
            "name": "Emoji",
            "summary": "",
            "url": "classes/App-Dto-Discord-Emoji.html"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Emoji\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Dto-Discord-Emoji.html#method___construct"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Emoji\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Dto-Discord-Emoji.html#property_id"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Emoji\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/App-Dto-Discord-Emoji.html#property_name"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Emoji\u003A\u003A\u0024roles",
            "name": "roles",
            "summary": "",
            "url": "classes/App-Dto-Discord-Emoji.html#property_roles"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Emoji\u003A\u003A\u0024user",
            "name": "user",
            "summary": "",
            "url": "classes/App-Dto-Discord-Emoji.html#property_user"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Emoji\u003A\u003A\u0024require_colons",
            "name": "require_colons",
            "summary": "",
            "url": "classes/App-Dto-Discord-Emoji.html#property_require_colons"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Emoji\u003A\u003A\u0024managed",
            "name": "managed",
            "summary": "",
            "url": "classes/App-Dto-Discord-Emoji.html#property_managed"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Emoji\u003A\u003A\u0024animated",
            "name": "animated",
            "summary": "",
            "url": "classes/App-Dto-Discord-Emoji.html#property_animated"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Emoji\u003A\u003A\u0024available",
            "name": "available",
            "summary": "",
            "url": "classes/App-Dto-Discord-Emoji.html#property_available"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild",
            "name": "Guild",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#method___construct"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024region",
            "name": "region",
            "summary": "Voice\u0020region\u0020id\u0020for\u0020the\u0020guild\u0020\u0028deprecated\u0029.",
            "url": "classes/App-Dto-Discord-Guild.html#property_region"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_id"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_name"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024icon",
            "name": "icon",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_icon"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024splash",
            "name": "splash",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_splash"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024discovery_splash",
            "name": "discovery_splash",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_discovery_splash"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024owner_id",
            "name": "owner_id",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_owner_id"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024afk_channel_id",
            "name": "afk_channel_id",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_afk_channel_id"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024afk_timeout",
            "name": "afk_timeout",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_afk_timeout"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024verification_level",
            "name": "verification_level",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_verification_level"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024default_message_notifications",
            "name": "default_message_notifications",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_default_message_notifications"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024explicit_content_filter",
            "name": "explicit_content_filter",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_explicit_content_filter"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024roles",
            "name": "roles",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_roles"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024emojis",
            "name": "emojis",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_emojis"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024features",
            "name": "features",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_features"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024mfa_level",
            "name": "mfa_level",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_mfa_level"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024application_id",
            "name": "application_id",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_application_id"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024system_channel_id",
            "name": "system_channel_id",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_system_channel_id"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024system_channel_flags",
            "name": "system_channel_flags",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_system_channel_flags"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024rules_channel_id",
            "name": "rules_channel_id",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_rules_channel_id"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024vanity_url_code",
            "name": "vanity_url_code",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_vanity_url_code"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_description"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024banner",
            "name": "banner",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_banner"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024premium_tier",
            "name": "premium_tier",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_premium_tier"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024preferred_locale",
            "name": "preferred_locale",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_preferred_locale"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024public_updates_channel_id",
            "name": "public_updates_channel_id",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_public_updates_channel_id"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024nsfw_level",
            "name": "nsfw_level",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_nsfw_level"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024premium_progress_bar_enabled",
            "name": "premium_progress_bar_enabled",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_premium_progress_bar_enabled"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024safety_alerts_channel_id",
            "name": "safety_alerts_channel_id",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_safety_alerts_channel_id"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024icon_hash",
            "name": "icon_hash",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_icon_hash"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024owner",
            "name": "owner",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_owner"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024permissions",
            "name": "permissions",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_permissions"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024widget_enabled",
            "name": "widget_enabled",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_widget_enabled"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024widget_channel_id",
            "name": "widget_channel_id",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_widget_channel_id"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024max_presences",
            "name": "max_presences",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_max_presences"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024max_members",
            "name": "max_members",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_max_members"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024premium_subscription_count",
            "name": "premium_subscription_count",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_premium_subscription_count"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024max_video_channel_users",
            "name": "max_video_channel_users",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_max_video_channel_users"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024max_stage_video_channel_users",
            "name": "max_stage_video_channel_users",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_max_stage_video_channel_users"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024approximate_member_count",
            "name": "approximate_member_count",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_approximate_member_count"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024approximate_presence_count",
            "name": "approximate_presence_count",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_approximate_presence_count"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024welcome_screen",
            "name": "welcome_screen",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_welcome_screen"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Guild\u003A\u003A\u0024stickers",
            "name": "stickers",
            "summary": "",
            "url": "classes/App-Dto-Discord-Guild.html#property_stickers"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Role",
            "name": "Role",
            "summary": "",
            "url": "classes/App-Dto-Discord-Role.html"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Role\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Dto-Discord-Role.html#method___construct"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Role\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Dto-Discord-Role.html#property_id"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Role\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/App-Dto-Discord-Role.html#property_name"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Role\u003A\u003A\u0024color",
            "name": "color",
            "summary": "",
            "url": "classes/App-Dto-Discord-Role.html#property_color"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Role\u003A\u003A\u0024hoist",
            "name": "hoist",
            "summary": "",
            "url": "classes/App-Dto-Discord-Role.html#property_hoist"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Role\u003A\u003A\u0024position",
            "name": "position",
            "summary": "",
            "url": "classes/App-Dto-Discord-Role.html#property_position"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Role\u003A\u003A\u0024permissions",
            "name": "permissions",
            "summary": "",
            "url": "classes/App-Dto-Discord-Role.html#property_permissions"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Role\u003A\u003A\u0024managed",
            "name": "managed",
            "summary": "",
            "url": "classes/App-Dto-Discord-Role.html#property_managed"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Role\u003A\u003A\u0024mentionable",
            "name": "mentionable",
            "summary": "",
            "url": "classes/App-Dto-Discord-Role.html#property_mentionable"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Role\u003A\u003A\u0024flags",
            "name": "flags",
            "summary": "",
            "url": "classes/App-Dto-Discord-Role.html#property_flags"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Role\u003A\u003A\u0024icon",
            "name": "icon",
            "summary": "",
            "url": "classes/App-Dto-Discord-Role.html#property_icon"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Role\u003A\u003A\u0024unicode_emoji",
            "name": "unicode_emoji",
            "summary": "",
            "url": "classes/App-Dto-Discord-Role.html#property_unicode_emoji"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Role\u003A\u003A\u0024tags",
            "name": "tags",
            "summary": "",
            "url": "classes/App-Dto-Discord-Role.html#property_tags"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\RoleTags",
            "name": "RoleTags",
            "summary": "",
            "url": "classes/App-Dto-Discord-RoleTags.html"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\RoleTags\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Dto-Discord-RoleTags.html#method___construct"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\RoleTags\u003A\u003AgetBotId\u0028\u0029",
            "name": "getBotId",
            "summary": "",
            "url": "classes/App-Dto-Discord-RoleTags.html#method_getBotId"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\RoleTags\u003A\u003AgetIntegrationId\u0028\u0029",
            "name": "getIntegrationId",
            "summary": "",
            "url": "classes/App-Dto-Discord-RoleTags.html#method_getIntegrationId"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\RoleTags\u003A\u003AgetPremiumSubscriber\u0028\u0029",
            "name": "getPremiumSubscriber",
            "summary": "",
            "url": "classes/App-Dto-Discord-RoleTags.html#method_getPremiumSubscriber"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\RoleTags\u003A\u003AgetSubscriptionListingId\u0028\u0029",
            "name": "getSubscriptionListingId",
            "summary": "",
            "url": "classes/App-Dto-Discord-RoleTags.html#method_getSubscriptionListingId"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\RoleTags\u003A\u003AgetAvailableForPurchase\u0028\u0029",
            "name": "getAvailableForPurchase",
            "summary": "",
            "url": "classes/App-Dto-Discord-RoleTags.html#method_getAvailableForPurchase"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\RoleTags\u003A\u003AgetGuildConnections\u0028\u0029",
            "name": "getGuildConnections",
            "summary": "",
            "url": "classes/App-Dto-Discord-RoleTags.html#method_getGuildConnections"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\RoleTags\u003A\u003Adenormalize\u0028\u0029",
            "name": "denormalize",
            "summary": "",
            "url": "classes/App-Dto-Discord-RoleTags.html#method_denormalize"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\RoleTags\u003A\u003A\u0024bot_id",
            "name": "bot_id",
            "summary": "",
            "url": "classes/App-Dto-Discord-RoleTags.html#property_bot_id"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\RoleTags\u003A\u003A\u0024integration_id",
            "name": "integration_id",
            "summary": "",
            "url": "classes/App-Dto-Discord-RoleTags.html#property_integration_id"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\RoleTags\u003A\u003A\u0024premium_subscriber",
            "name": "premium_subscriber",
            "summary": "",
            "url": "classes/App-Dto-Discord-RoleTags.html#property_premium_subscriber"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\RoleTags\u003A\u003A\u0024subscription_listing_id",
            "name": "subscription_listing_id",
            "summary": "",
            "url": "classes/App-Dto-Discord-RoleTags.html#property_subscription_listing_id"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\RoleTags\u003A\u003A\u0024available_for_purchase",
            "name": "available_for_purchase",
            "summary": "",
            "url": "classes/App-Dto-Discord-RoleTags.html#property_available_for_purchase"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\RoleTags\u003A\u003A\u0024guild_connections",
            "name": "guild_connections",
            "summary": "",
            "url": "classes/App-Dto-Discord-RoleTags.html#property_guild_connections"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Sticker",
            "name": "Sticker",
            "summary": "",
            "url": "classes/App-Dto-Discord-Sticker.html"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Sticker\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Dto-Discord-Sticker.html#method___construct"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Sticker\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Dto-Discord-Sticker.html#property_id"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Sticker\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/App-Dto-Discord-Sticker.html#property_name"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Sticker\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/App-Dto-Discord-Sticker.html#property_description"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Sticker\u003A\u003A\u0024tags",
            "name": "tags",
            "summary": "",
            "url": "classes/App-Dto-Discord-Sticker.html#property_tags"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Sticker\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/App-Dto-Discord-Sticker.html#property_type"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Sticker\u003A\u003A\u0024format_type",
            "name": "format_type",
            "summary": "",
            "url": "classes/App-Dto-Discord-Sticker.html#property_format_type"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Sticker\u003A\u003A\u0024pack_id",
            "name": "pack_id",
            "summary": "",
            "url": "classes/App-Dto-Discord-Sticker.html#property_pack_id"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Sticker\u003A\u003A\u0024available",
            "name": "available",
            "summary": "",
            "url": "classes/App-Dto-Discord-Sticker.html#property_available"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Sticker\u003A\u003A\u0024guild_id",
            "name": "guild_id",
            "summary": "",
            "url": "classes/App-Dto-Discord-Sticker.html#property_guild_id"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Sticker\u003A\u003A\u0024user",
            "name": "user",
            "summary": "",
            "url": "classes/App-Dto-Discord-Sticker.html#property_user"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\Sticker\u003A\u003A\u0024sort_value",
            "name": "sort_value",
            "summary": "",
            "url": "classes/App-Dto-Discord-Sticker.html#property_sort_value"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\User",
            "name": "User",
            "summary": "",
            "url": "classes/App-Dto-Discord-User.html"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\User\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Dto-Discord-User.html#method___construct"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\User\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Dto-Discord-User.html#property_id"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\User\u003A\u003A\u0024username",
            "name": "username",
            "summary": "",
            "url": "classes/App-Dto-Discord-User.html#property_username"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\User\u003A\u003A\u0024discriminator",
            "name": "discriminator",
            "summary": "",
            "url": "classes/App-Dto-Discord-User.html#property_discriminator"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\User\u003A\u003A\u0024global_name",
            "name": "global_name",
            "summary": "",
            "url": "classes/App-Dto-Discord-User.html#property_global_name"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\User\u003A\u003A\u0024avatar",
            "name": "avatar",
            "summary": "",
            "url": "classes/App-Dto-Discord-User.html#property_avatar"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\User\u003A\u003A\u0024bot",
            "name": "bot",
            "summary": "",
            "url": "classes/App-Dto-Discord-User.html#property_bot"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\User\u003A\u003A\u0024system",
            "name": "system",
            "summary": "",
            "url": "classes/App-Dto-Discord-User.html#property_system"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\User\u003A\u003A\u0024mfa_enabled",
            "name": "mfa_enabled",
            "summary": "",
            "url": "classes/App-Dto-Discord-User.html#property_mfa_enabled"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\User\u003A\u003A\u0024banner",
            "name": "banner",
            "summary": "",
            "url": "classes/App-Dto-Discord-User.html#property_banner"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\User\u003A\u003A\u0024accent_color",
            "name": "accent_color",
            "summary": "",
            "url": "classes/App-Dto-Discord-User.html#property_accent_color"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\User\u003A\u003A\u0024locale",
            "name": "locale",
            "summary": "",
            "url": "classes/App-Dto-Discord-User.html#property_locale"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\User\u003A\u003A\u0024verified",
            "name": "verified",
            "summary": "",
            "url": "classes/App-Dto-Discord-User.html#property_verified"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\User\u003A\u003A\u0024email",
            "name": "email",
            "summary": "",
            "url": "classes/App-Dto-Discord-User.html#property_email"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\User\u003A\u003A\u0024flags",
            "name": "flags",
            "summary": "",
            "url": "classes/App-Dto-Discord-User.html#property_flags"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\User\u003A\u003A\u0024premium_type",
            "name": "premium_type",
            "summary": "",
            "url": "classes/App-Dto-Discord-User.html#property_premium_type"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\User\u003A\u003A\u0024public_flags",
            "name": "public_flags",
            "summary": "",
            "url": "classes/App-Dto-Discord-User.html#property_public_flags"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\User\u003A\u003A\u0024avatar_decoration_data",
            "name": "avatar_decoration_data",
            "summary": "",
            "url": "classes/App-Dto-Discord-User.html#property_avatar_decoration_data"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\WebhookEventBody",
            "name": "WebhookEventBody",
            "summary": "",
            "url": "classes/App-Dto-Discord-WebhookEventBody.html"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\WebhookEventBody\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Dto-Discord-WebhookEventBody.html#method___construct"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\WebhookEventBody\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/App-Dto-Discord-WebhookEventBody.html#property_type"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\WebhookEventBody\u003A\u003A\u0024timestamp",
            "name": "timestamp",
            "summary": "",
            "url": "classes/App-Dto-Discord-WebhookEventBody.html#property_timestamp"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\WebhookEventPayload",
            "name": "WebhookEventPayload",
            "summary": "",
            "url": "classes/App-Dto-Discord-WebhookEventPayload.html"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\WebhookEventPayload\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Dto-Discord-WebhookEventPayload.html#method___construct"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\WebhookEventPayload\u003A\u003A\u0024version",
            "name": "version",
            "summary": "",
            "url": "classes/App-Dto-Discord-WebhookEventPayload.html#property_version"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\WebhookEventPayload\u003A\u003A\u0024application_id",
            "name": "application_id",
            "summary": "",
            "url": "classes/App-Dto-Discord-WebhookEventPayload.html#property_application_id"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\WebhookEventPayload\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/App-Dto-Discord-WebhookEventPayload.html#property_type"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\WebhookEventPayload\u003A\u003A\u0024event",
            "name": "event",
            "summary": "",
            "url": "classes/App-Dto-Discord-WebhookEventPayload.html#property_event"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\WelcomeScreen",
            "name": "WelcomeScreen",
            "summary": "",
            "url": "classes/App-Dto-Discord-WelcomeScreen.html"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\WelcomeScreen\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Dto-Discord-WelcomeScreen.html#method___construct"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\WelcomeScreen\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/App-Dto-Discord-WelcomeScreen.html#property_description"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\WelcomeScreen\u003A\u003A\u0024welcome_channels",
            "name": "welcome_channels",
            "summary": "",
            "url": "classes/App-Dto-Discord-WelcomeScreen.html#property_welcome_channels"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\WelcomeScreenChannel",
            "name": "WelcomeScreenChannel",
            "summary": "",
            "url": "classes/App-Dto-Discord-WelcomeScreenChannel.html"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\WelcomeScreenChannel\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Dto-Discord-WelcomeScreenChannel.html#method___construct"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\WelcomeScreenChannel\u003A\u003A\u0024channel_id",
            "name": "channel_id",
            "summary": "",
            "url": "classes/App-Dto-Discord-WelcomeScreenChannel.html#property_channel_id"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\WelcomeScreenChannel\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/App-Dto-Discord-WelcomeScreenChannel.html#property_description"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\WelcomeScreenChannel\u003A\u003A\u0024emoji_id",
            "name": "emoji_id",
            "summary": "",
            "url": "classes/App-Dto-Discord-WelcomeScreenChannel.html#property_emoji_id"
        },                {
            "fqsen": "\\App\\Dto\\Discord\\WelcomeScreenChannel\u003A\u003A\u0024emoji_name",
            "name": "emoji_name",
            "summary": "",
            "url": "classes/App-Dto-Discord-WelcomeScreenChannel.html#property_emoji_name"
        },                {
            "fqsen": "\\App\\Entity\\Guild",
            "name": "Guild",
            "summary": "",
            "url": "classes/App-Entity-Guild.html"
        },                {
            "fqsen": "\\App\\Entity\\Guild\u003A\u003AgetInstalled\u0028\u0029",
            "name": "getInstalled",
            "summary": "",
            "url": "classes/App-Entity-Guild.html#method_getInstalled"
        },                {
            "fqsen": "\\App\\Entity\\Guild\u003A\u003AsetInstalled\u0028\u0029",
            "name": "setInstalled",
            "summary": "",
            "url": "classes/App-Entity-Guild.html#method_setInstalled"
        },                {
            "fqsen": "\\App\\Entity\\Guild\u003A\u003A\u0024installed",
            "name": "installed",
            "summary": "",
            "url": "classes/App-Entity-Guild.html#property_installed"
        },                {
            "fqsen": "\\App\\Entity\\Traits\\DiscordIdentifiable",
            "name": "DiscordIdentifiable",
            "summary": "",
            "url": "classes/App-Entity-Traits-DiscordIdentifiable.html"
        },                {
            "fqsen": "\\App\\Entity\\Traits\\DiscordIdentifiable\u003A\u003AgetDiscordId\u0028\u0029",
            "name": "getDiscordId",
            "summary": "",
            "url": "classes/App-Entity-Traits-DiscordIdentifiable.html#method_getDiscordId"
        },                {
            "fqsen": "\\App\\Entity\\Traits\\DiscordIdentifiable\u003A\u003AsetDiscordId\u0028\u0029",
            "name": "setDiscordId",
            "summary": "",
            "url": "classes/App-Entity-Traits-DiscordIdentifiable.html#method_setDiscordId"
        },                {
            "fqsen": "\\App\\Entity\\Traits\\DiscordIdentifiable\u003A\u003A\u0024discordId",
            "name": "discordId",
            "summary": "",
            "url": "classes/App-Entity-Traits-DiscordIdentifiable.html#property_discordId"
        },                {
            "fqsen": "\\App\\Entity\\Traits\\Identifiable",
            "name": "Identifiable",
            "summary": "",
            "url": "classes/App-Entity-Traits-Identifiable.html"
        },                {
            "fqsen": "\\App\\Entity\\Traits\\Identifiable\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-Traits-Identifiable.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Traits\\Identifiable\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Traits-Identifiable.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Traits\\Timestampable",
            "name": "Timestampable",
            "summary": "",
            "url": "classes/App-Entity-Traits-Timestampable.html"
        },                {
            "fqsen": "\\App\\Entity\\Traits\\Timestampable\u003A\u003AgetCreatedAt\u0028\u0029",
            "name": "getCreatedAt",
            "summary": "",
            "url": "classes/App-Entity-Traits-Timestampable.html#method_getCreatedAt"
        },                {
            "fqsen": "\\App\\Entity\\Traits\\Timestampable\u003A\u003AsetCreatedAt\u0028\u0029",
            "name": "setCreatedAt",
            "summary": "",
            "url": "classes/App-Entity-Traits-Timestampable.html#method_setCreatedAt"
        },                {
            "fqsen": "\\App\\Entity\\Traits\\Timestampable\u003A\u003AgetUpdatedAt\u0028\u0029",
            "name": "getUpdatedAt",
            "summary": "",
            "url": "classes/App-Entity-Traits-Timestampable.html#method_getUpdatedAt"
        },                {
            "fqsen": "\\App\\Entity\\Traits\\Timestampable\u003A\u003AsetUpdatedAt\u0028\u0029",
            "name": "setUpdatedAt",
            "summary": "",
            "url": "classes/App-Entity-Traits-Timestampable.html#method_setUpdatedAt"
        },                {
            "fqsen": "\\App\\Entity\\Traits\\Timestampable\u003A\u003A\u0024createdAt",
            "name": "createdAt",
            "summary": "",
            "url": "classes/App-Entity-Traits-Timestampable.html#property_createdAt"
        },                {
            "fqsen": "\\App\\Entity\\Traits\\Timestampable\u003A\u003A\u0024updatedAt",
            "name": "updatedAt",
            "summary": "",
            "url": "classes/App-Entity-Traits-Timestampable.html#property_updatedAt"
        },                {
            "fqsen": "\\App\\Entity\\User",
            "name": "User",
            "summary": "",
            "url": "classes/App-Entity-User.html"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetRoles\u0028\u0029",
            "name": "getRoles",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getRoles"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetRoles\u0028\u0029",
            "name": "setRoles",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_setRoles"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetUserIdentifier\u0028\u0029",
            "name": "getUserIdentifier",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getUserIdentifier"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AeraseCredentials\u0028\u0029",
            "name": "eraseCredentials",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_eraseCredentials"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AROLE_USER",
            "name": "ROLE_USER",
            "summary": "",
            "url": "classes/App-Entity-User.html#constant_ROLE_USER"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AROLE_SUPER_ADMIN",
            "name": "ROLE_SUPER_ADMIN",
            "summary": "",
            "url": "classes/App-Entity-User.html#constant_ROLE_SUPER_ADMIN"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024roles",
            "name": "roles",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_roles"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\DefaultMessageNotificationLevel",
            "name": "DefaultMessageNotificationLevel",
            "summary": "",
            "url": "classes/App-Enum-Discord-DefaultMessageNotificationLevel.html"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\DefaultMessageNotificationLevel\u003A\u003AALL_MESSAGES",
            "name": "ALL_MESSAGES",
            "summary": "Members\u0020will\u0020receive\u0020notifications\u0020for\u0020all\u0020messages\u0020by\u0020default.",
            "url": "classes/App-Enum-Discord-DefaultMessageNotificationLevel.html#enumcase_ALL_MESSAGES"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\DefaultMessageNotificationLevel\u003A\u003AONLY_MENTIONS",
            "name": "ONLY_MENTIONS",
            "summary": "Members\u0020will\u0020receive\u0020notifications\u0020only\u0020for\u0020messages\u0020that\u0020\u0040mention\u0020them\u0020by\u0020default.",
            "url": "classes/App-Enum-Discord-DefaultMessageNotificationLevel.html#enumcase_ONLY_MENTIONS"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\ExplicitContentFilterLevel",
            "name": "ExplicitContentFilterLevel",
            "summary": "",
            "url": "classes/App-Enum-Discord-ExplicitContentFilterLevel.html"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\ExplicitContentFilterLevel\u003A\u003ADISABLED",
            "name": "DISABLED",
            "summary": "Media\u0020content\u0020will\u0020not\u0020be\u0020scanned.",
            "url": "classes/App-Enum-Discord-ExplicitContentFilterLevel.html#enumcase_DISABLED"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\ExplicitContentFilterLevel\u003A\u003AMEMBERS_WITHOUT_ROLES",
            "name": "MEMBERS_WITHOUT_ROLES",
            "summary": "Media\u0020content\u0020sent\u0020by\u0020members\u0020without\u0020roles\u0020will\u0020be\u0020scanned.",
            "url": "classes/App-Enum-Discord-ExplicitContentFilterLevel.html#enumcase_MEMBERS_WITHOUT_ROLES"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\ExplicitContentFilterLevel\u003A\u003AALL_MEMBERS",
            "name": "ALL_MEMBERS",
            "summary": "Media\u0020content\u0020sent\u0020by\u0020all\u0020members\u0020will\u0020be\u0020scanned.",
            "url": "classes/App-Enum-Discord-ExplicitContentFilterLevel.html#enumcase_ALL_MEMBERS"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\GuildNsfwLevel",
            "name": "GuildNsfwLevel",
            "summary": "",
            "url": "classes/App-Enum-Discord-GuildNsfwLevel.html"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\GuildNsfwLevel\u003A\u003ADEFAULT",
            "name": "DEFAULT",
            "summary": "",
            "url": "classes/App-Enum-Discord-GuildNsfwLevel.html#enumcase_DEFAULT"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\GuildNsfwLevel\u003A\u003AEXPLICIT",
            "name": "EXPLICIT",
            "summary": "",
            "url": "classes/App-Enum-Discord-GuildNsfwLevel.html#enumcase_EXPLICIT"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\GuildNsfwLevel\u003A\u003ASAFE",
            "name": "SAFE",
            "summary": "",
            "url": "classes/App-Enum-Discord-GuildNsfwLevel.html#enumcase_SAFE"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\GuildNsfwLevel\u003A\u003AAGE_RESTRICTED",
            "name": "AGE_RESTRICTED",
            "summary": "",
            "url": "classes/App-Enum-Discord-GuildNsfwLevel.html#enumcase_AGE_RESTRICTED"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\MfaLevel",
            "name": "MfaLevel",
            "summary": "",
            "url": "classes/App-Enum-Discord-MfaLevel.html"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\MfaLevel\u003A\u003ANONE",
            "name": "NONE",
            "summary": "Guild\u0020has\u0020no\u0020MFA\/2FA\u0020requirement\u0020for\u0020moderation\u0020actions.",
            "url": "classes/App-Enum-Discord-MfaLevel.html#enumcase_NONE"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\MfaLevel\u003A\u003AELEVATED",
            "name": "ELEVATED",
            "summary": "Guild\u0020has\u0020a\u00202FA\u0020requirement\u0020for\u0020moderation\u0020actions.",
            "url": "classes/App-Enum-Discord-MfaLevel.html#enumcase_ELEVATED"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\PremiumTier",
            "name": "PremiumTier",
            "summary": "",
            "url": "classes/App-Enum-Discord-PremiumTier.html"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\PremiumTier\u003A\u003ANONE",
            "name": "NONE",
            "summary": "Guild\u0020has\u0020not\u0020unlocked\u0020any\u0020Server\u0020Boost\u0020perks.",
            "url": "classes/App-Enum-Discord-PremiumTier.html#enumcase_NONE"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\PremiumTier\u003A\u003ATIER_1",
            "name": "TIER_1",
            "summary": "Guild\u0020has\u0020unlocked\u0020Server\u0020Boost\u0020level\u00201\u0020perks.",
            "url": "classes/App-Enum-Discord-PremiumTier.html#enumcase_TIER_1"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\PremiumTier\u003A\u003ATIER_2",
            "name": "TIER_2",
            "summary": "Guild\u0020has\u0020unlocked\u0020Server\u0020Boost\u0020level\u00202\u0020perks",
            "url": "classes/App-Enum-Discord-PremiumTier.html#enumcase_TIER_2"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\PremiumTier\u003A\u003ATIER_3",
            "name": "TIER_3",
            "summary": "Guild\u0020has\u0020unlocked\u0020Server\u0020Boost\u0020level\u00203\u0020perks.",
            "url": "classes/App-Enum-Discord-PremiumTier.html#enumcase_TIER_3"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\PremiumType",
            "name": "PremiumType",
            "summary": "",
            "url": "classes/App-Enum-Discord-PremiumType.html"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\PremiumType\u003A\u003ANone",
            "name": "None",
            "summary": "",
            "url": "classes/App-Enum-Discord-PremiumType.html#enumcase_None"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\PremiumType\u003A\u003ANitroClassic",
            "name": "NitroClassic",
            "summary": "",
            "url": "classes/App-Enum-Discord-PremiumType.html#enumcase_NitroClassic"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\PremiumType\u003A\u003ANitro",
            "name": "Nitro",
            "summary": "",
            "url": "classes/App-Enum-Discord-PremiumType.html#enumcase_Nitro"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\PremiumType\u003A\u003ANitroBasic",
            "name": "NitroBasic",
            "summary": "",
            "url": "classes/App-Enum-Discord-PremiumType.html#enumcase_NitroBasic"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\StickerFormatType",
            "name": "StickerFormatType",
            "summary": "",
            "url": "classes/App-Enum-Discord-StickerFormatType.html"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\StickerFormatType\u003A\u003APNG",
            "name": "PNG",
            "summary": "",
            "url": "classes/App-Enum-Discord-StickerFormatType.html#enumcase_PNG"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\StickerFormatType\u003A\u003AAPNG",
            "name": "APNG",
            "summary": "",
            "url": "classes/App-Enum-Discord-StickerFormatType.html#enumcase_APNG"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\StickerFormatType\u003A\u003ALOTTIE",
            "name": "LOTTIE",
            "summary": "",
            "url": "classes/App-Enum-Discord-StickerFormatType.html#enumcase_LOTTIE"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\StickerFormatType\u003A\u003AGIF",
            "name": "GIF",
            "summary": "",
            "url": "classes/App-Enum-Discord-StickerFormatType.html#enumcase_GIF"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\StickerType",
            "name": "StickerType",
            "summary": "",
            "url": "classes/App-Enum-Discord-StickerType.html"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\StickerType\u003A\u003ASTANDARD",
            "name": "STANDARD",
            "summary": "An\u0020official\u0020sticker\u0020in\u0020a\u0020pack.",
            "url": "classes/App-Enum-Discord-StickerType.html#enumcase_STANDARD"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\StickerType\u003A\u003AGUILD",
            "name": "GUILD",
            "summary": "A\u0020sticker\u0020uploaded\u0020to\u0020a\u0020guild\u0020for\u0020the\u0020guild\u0027s\u0020members.",
            "url": "classes/App-Enum-Discord-StickerType.html#enumcase_GUILD"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\VerificationLevel",
            "name": "VerificationLevel",
            "summary": "",
            "url": "classes/App-Enum-Discord-VerificationLevel.html"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\VerificationLevel\u003A\u003ANONE",
            "name": "NONE",
            "summary": "Unrestricted.",
            "url": "classes/App-Enum-Discord-VerificationLevel.html#enumcase_NONE"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\VerificationLevel\u003A\u003ALOW",
            "name": "LOW",
            "summary": "Must\u0020have\u0020verified\u0020email\u0020on\u0020account.",
            "url": "classes/App-Enum-Discord-VerificationLevel.html#enumcase_LOW"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\VerificationLevel\u003A\u003AMEDIUM",
            "name": "MEDIUM",
            "summary": "Must\u0020be\u0020registered\u0020on\u0020Discord\u0020for\u0020longer\u0020than\u00205\u0020minutes.",
            "url": "classes/App-Enum-Discord-VerificationLevel.html#enumcase_MEDIUM"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\VerificationLevel\u003A\u003AHIGH",
            "name": "HIGH",
            "summary": "Must\u0020be\u0020a\u0020member\u0020of\u0020the\u0020server\u0020for\u0020longer\u0020than\u002010\u0020minutes.",
            "url": "classes/App-Enum-Discord-VerificationLevel.html#enumcase_HIGH"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\VerificationLevel\u003A\u003AVERY_HIGH",
            "name": "VERY_HIGH",
            "summary": "Must\u0020have\u0020a\u0020verified\u0020phone\u0020number.",
            "url": "classes/App-Enum-Discord-VerificationLevel.html#enumcase_VERY_HIGH"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\WebhookEventBodyType",
            "name": "WebhookEventBodyType",
            "summary": "",
            "url": "classes/App-Enum-Discord-WebhookEventBodyType.html"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\WebhookEventBodyType\u003A\u003AApplicationAuthorized",
            "name": "ApplicationAuthorized",
            "summary": "Sent\u0020when\u0020an\u0020app\u0020was\u0020authorized\u0020by\u0020a\u0020user\u0020to\u0020a\u0020server\u0020or\u0020their\u0020account",
            "url": "classes/App-Enum-Discord-WebhookEventBodyType.html#enumcase_ApplicationAuthorized"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\WebhookEventBodyType\u003A\u003AEntitlementCreate",
            "name": "EntitlementCreate",
            "summary": "Entitlement\u0020was\u0020created.",
            "url": "classes/App-Enum-Discord-WebhookEventBodyType.html#enumcase_EntitlementCreate"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\WebhookEventBodyType\u003A\u003AQuestUserEnrollment",
            "name": "QuestUserEnrollment",
            "summary": "User\u0020was\u0020added\u0020to\u0020a\u0020Quest\u0020\u0028currently\u0020unavailable\u0029",
            "url": "classes/App-Enum-Discord-WebhookEventBodyType.html#enumcase_QuestUserEnrollment"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\WebhookType",
            "name": "WebhookType",
            "summary": "",
            "url": "classes/App-Enum-Discord-WebhookType.html"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\WebhookType\u003A\u003APING",
            "name": "PING",
            "summary": "PING\u0020event\u0020sent\u0020to\u0020verify\u0020your\u0020Webhook\u0020Event\u0020URL\u0020is\u0020active.",
            "url": "classes/App-Enum-Discord-WebhookType.html#enumcase_PING"
        },                {
            "fqsen": "\\App\\Enum\\Discord\\WebhookType\u003A\u003AEvent",
            "name": "Event",
            "summary": "Webhook\u0020event\u0020\u0028details\u0020for\u0020event\u0020in\u0020event\u0020body\u0020object\u0029.",
            "url": "classes/App-Enum-Discord-WebhookType.html#enumcase_Event"
        },                {
            "fqsen": "\\App\\Kernel",
            "name": "Kernel",
            "summary": "",
            "url": "classes/App-Kernel.html"
        },                {
            "fqsen": "\\App\\Repository\\GuildRepository",
            "name": "GuildRepository",
            "summary": "",
            "url": "classes/App-Repository-GuildRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\GuildRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-GuildRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\GuildRepository\u003A\u003AfindOneByDiscordId\u0028\u0029",
            "name": "findOneByDiscordId",
            "summary": "",
            "url": "classes/App-Repository-GuildRepository.html#method_findOneByDiscordId"
        },                {
            "fqsen": "\\App\\Repository\\Traits\\Alterable",
            "name": "Alterable",
            "summary": "",
            "url": "classes/App-Repository-Traits-Alterable.html"
        },                {
            "fqsen": "\\App\\Repository\\Traits\\Alterable\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "",
            "url": "classes/App-Repository-Traits-Alterable.html#method_add"
        },                {
            "fqsen": "\\App\\Repository\\Traits\\Alterable\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "",
            "url": "classes/App-Repository-Traits-Alterable.html#method_remove"
        },                {
            "fqsen": "\\App\\Repository\\UserRepository",
            "name": "UserRepository",
            "summary": "",
            "url": "classes/App-Repository-UserRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\UserRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-UserRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\UserRepository\u003A\u003AfindOneByUserIdentifier\u0028\u0029",
            "name": "findOneByUserIdentifier",
            "summary": "",
            "url": "classes/App-Repository-UserRepository.html#method_findOneByUserIdentifier"
        },                {
            "fqsen": "\\App\\Repository\\UserRepository\u003A\u003AfindOneByDiscordId\u0028\u0029",
            "name": "findOneByDiscordId",
            "summary": "",
            "url": "classes/App-Repository-UserRepository.html#method_findOneByDiscordId"
        },                {
            "fqsen": "\\App\\Security\\Discord\\RequestAuthenticator",
            "name": "RequestAuthenticator",
            "summary": "",
            "url": "classes/App-Security-Discord-RequestAuthenticator.html"
        },                {
            "fqsen": "\\App\\Security\\Discord\\RequestAuthenticator\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Security-Discord-RequestAuthenticator.html#method___construct"
        },                {
            "fqsen": "\\App\\Security\\Discord\\RequestAuthenticator\u003A\u003Asupports\u0028\u0029",
            "name": "supports",
            "summary": "",
            "url": "classes/App-Security-Discord-RequestAuthenticator.html#method_supports"
        },                {
            "fqsen": "\\App\\Security\\Discord\\RequestAuthenticator\u003A\u003Aauthenticate\u0028\u0029",
            "name": "authenticate",
            "summary": "",
            "url": "classes/App-Security-Discord-RequestAuthenticator.html#method_authenticate"
        },                {
            "fqsen": "\\App\\Security\\Discord\\RequestAuthenticator\u003A\u003AonAuthenticationSuccess\u0028\u0029",
            "name": "onAuthenticationSuccess",
            "summary": "",
            "url": "classes/App-Security-Discord-RequestAuthenticator.html#method_onAuthenticationSuccess"
        },                {
            "fqsen": "\\App\\Security\\Discord\\RequestAuthenticator\u003A\u003AonAuthenticationFailure\u0028\u0029",
            "name": "onAuthenticationFailure",
            "summary": "",
            "url": "classes/App-Security-Discord-RequestAuthenticator.html#method_onAuthenticationFailure"
        },                {
            "fqsen": "\\App\\Security\\Discord\\RequestAuthenticator\u003A\u003AresolveUserIdentifier\u0028\u0029",
            "name": "resolveUserIdentifier",
            "summary": "",
            "url": "classes/App-Security-Discord-RequestAuthenticator.html#method_resolveUserIdentifier"
        },                {
            "fqsen": "\\App\\Security\\Discord\\RequestAuthenticator\u003A\u003AfindOrCreateUser\u0028\u0029",
            "name": "findOrCreateUser",
            "summary": "",
            "url": "classes/App-Security-Discord-RequestAuthenticator.html#method_findOrCreateUser"
        },                {
            "fqsen": "\\App\\Security\\Discord\\RequestAuthenticator\u003A\u003ADISCORD_AGENT_USER_IDENTIFIER",
            "name": "DISCORD_AGENT_USER_IDENTIFIER",
            "summary": "",
            "url": "classes/App-Security-Discord-RequestAuthenticator.html#constant_DISCORD_AGENT_USER_IDENTIFIER"
        },                {
            "fqsen": "\\App\\Security\\Discord\\RequestAuthenticator\u003A\u003A\u0024requestValidator",
            "name": "requestValidator",
            "summary": "",
            "url": "classes/App-Security-Discord-RequestAuthenticator.html#property_requestValidator"
        },                {
            "fqsen": "\\App\\Security\\Discord\\RequestAuthenticator\u003A\u003A\u0024logger",
            "name": "logger",
            "summary": "",
            "url": "classes/App-Security-Discord-RequestAuthenticator.html#property_logger"
        },                {
            "fqsen": "\\App\\Security\\Discord\\RequestAuthenticator\u003A\u003A\u0024userRepository",
            "name": "userRepository",
            "summary": "",
            "url": "classes/App-Security-Discord-RequestAuthenticator.html#property_userRepository"
        },                {
            "fqsen": "\\App\\Security\\Discord\\RequestAuthenticator\u003A\u003A\u0024validator",
            "name": "validator",
            "summary": "",
            "url": "classes/App-Security-Discord-RequestAuthenticator.html#property_validator"
        },                {
            "fqsen": "\\App\\Security\\Discord\\RequestValidator",
            "name": "RequestValidator",
            "summary": "",
            "url": "classes/App-Security-Discord-RequestValidator.html"
        },                {
            "fqsen": "\\App\\Security\\Discord\\RequestValidator\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Security-Discord-RequestValidator.html#method___construct"
        },                {
            "fqsen": "\\App\\Security\\Discord\\RequestValidator\u003A\u003Avalidate\u0028\u0029",
            "name": "validate",
            "summary": "",
            "url": "classes/App-Security-Discord-RequestValidator.html#method_validate"
        },                {
            "fqsen": "\\App\\Security\\Discord\\RequestValidator\u003A\u003AHEADER_ED25519",
            "name": "HEADER_ED25519",
            "summary": "",
            "url": "classes/App-Security-Discord-RequestValidator.html#constant_HEADER_ED25519"
        },                {
            "fqsen": "\\App\\Security\\Discord\\RequestValidator\u003A\u003AHEADER_TIMESTAMP",
            "name": "HEADER_TIMESTAMP",
            "summary": "",
            "url": "classes/App-Security-Discord-RequestValidator.html#constant_HEADER_TIMESTAMP"
        },                {
            "fqsen": "\\App\\Security\\Discord\\RequestValidator\u003A\u003A\u0024ec",
            "name": "ec",
            "summary": "",
            "url": "classes/App-Security-Discord-RequestValidator.html#property_ec"
        },                {
            "fqsen": "\\App\\Security\\Discord\\RequestValidator\u003A\u003A\u0024publicKey",
            "name": "publicKey",
            "summary": "",
            "url": "classes/App-Security-Discord-RequestValidator.html#property_publicKey"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Command",
            "name": "Command",
            "summary": "",
            "url": "namespaces/app-command.html"
        },                {
            "fqsen": "\\App\\Console",
            "name": "Console",
            "summary": "",
            "url": "namespaces/app-console.html"
        },                {
            "fqsen": "\\App\\Console\\Style",
            "name": "Style",
            "summary": "",
            "url": "namespaces/app-console-style.html"
        },                {
            "fqsen": "\\App\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "namespaces/app-controller.html"
        },                {
            "fqsen": "\\App\\DependencyInjection",
            "name": "DependencyInjection",
            "summary": "",
            "url": "namespaces/app-dependencyinjection.html"
        },                {
            "fqsen": "\\App\\Dto\\Discord",
            "name": "Discord",
            "summary": "",
            "url": "namespaces/app-dto-discord.html"
        },                {
            "fqsen": "\\App\\Dto",
            "name": "Dto",
            "summary": "",
            "url": "namespaces/app-dto.html"
        },                {
            "fqsen": "\\App\\Entity",
            "name": "Entity",
            "summary": "",
            "url": "namespaces/app-entity.html"
        },                {
            "fqsen": "\\App\\Entity\\Traits",
            "name": "Traits",
            "summary": "",
            "url": "namespaces/app-entity-traits.html"
        },                {
            "fqsen": "\\App\\Enum\\Discord",
            "name": "Discord",
            "summary": "",
            "url": "namespaces/app-enum-discord.html"
        },                {
            "fqsen": "\\App\\Enum",
            "name": "Enum",
            "summary": "",
            "url": "namespaces/app-enum.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Repository",
            "name": "Repository",
            "summary": "",
            "url": "namespaces/app-repository.html"
        },                {
            "fqsen": "\\App\\Repository\\Traits",
            "name": "Traits",
            "summary": "",
            "url": "namespaces/app-repository-traits.html"
        },                {
            "fqsen": "\\App\\Security\\Discord",
            "name": "Discord",
            "summary": "",
            "url": "namespaces/app-security-discord.html"
        },                {
            "fqsen": "\\App\\Security",
            "name": "Security",
            "summary": "",
            "url": "namespaces/app-security.html"
        }            ]
);
