Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Command\\UserDemoteCommand",
            "name": "UserDemoteCommand",
            "summary": "",
            "url": "classes/App-Command-UserDemoteCommand.html"
        },                {
            "fqsen": "\\App\\Command\\UserDemoteCommand\u003A\u003Aconfigure\u0028\u0029",
            "name": "configure",
            "summary": "",
            "url": "classes/App-Command-UserDemoteCommand.html#method_configure"
        },                {
            "fqsen": "\\App\\Command\\UserDemoteCommand\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "",
            "url": "classes/App-Command-UserDemoteCommand.html#method_execute"
        },                {
            "fqsen": "\\App\\Command\\UserListCommand",
            "name": "UserListCommand",
            "summary": "",
            "url": "classes/App-Command-UserListCommand.html"
        },                {
            "fqsen": "\\App\\Command\\UserListCommand\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "",
            "url": "classes/App-Command-UserListCommand.html#method_execute"
        },                {
            "fqsen": "\\App\\Command\\UserPromoteCommand",
            "name": "UserPromoteCommand",
            "summary": "",
            "url": "classes/App-Command-UserPromoteCommand.html"
        },                {
            "fqsen": "\\App\\Command\\UserPromoteCommand\u003A\u003Aconfigure\u0028\u0029",
            "name": "configure",
            "summary": "",
            "url": "classes/App-Command-UserPromoteCommand.html#method_configure"
        },                {
            "fqsen": "\\App\\Command\\UserPromoteCommand\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "",
            "url": "classes/App-Command-UserPromoteCommand.html#method_execute"
        },                {
            "fqsen": "\\App\\Console\\Command",
            "name": "Command",
            "summary": "",
            "url": "classes/App-Console-Command.html"
        },                {
            "fqsen": "\\App\\Console\\Command\u003A\u003AsetDefinitionListConverter\u0028\u0029",
            "name": "setDefinitionListConverter",
            "summary": "",
            "url": "classes/App-Console-Command.html#method_setDefinitionListConverter"
        },                {
            "fqsen": "\\App\\Console\\Command\u003A\u003Ainitialize\u0028\u0029",
            "name": "initialize",
            "summary": "",
            "url": "classes/App-Console-Command.html#method_initialize"
        },                {
            "fqsen": "\\App\\Console\\Command\u003A\u003ASUCCESS",
            "name": "SUCCESS",
            "summary": "",
            "url": "classes/App-Console-Command.html#constant_SUCCESS"
        },                {
            "fqsen": "\\App\\Console\\Command\u003A\u003AFAILURE",
            "name": "FAILURE",
            "summary": "",
            "url": "classes/App-Console-Command.html#constant_FAILURE"
        },                {
            "fqsen": "\\App\\Console\\Command\u003A\u003AINVALID",
            "name": "INVALID",
            "summary": "",
            "url": "classes/App-Console-Command.html#constant_INVALID"
        },                {
            "fqsen": "\\App\\Console\\Command\u003A\u003A\u0024io",
            "name": "io",
            "summary": "",
            "url": "classes/App-Console-Command.html#property_io"
        },                {
            "fqsen": "\\App\\Console\\Command\u003A\u003A\u0024definitionListConverter",
            "name": "definitionListConverter",
            "summary": "",
            "url": "classes/App-Console-Command.html#property_definitionListConverter"
        },                {
            "fqsen": "\\App\\Console\\Style\\DefinitionListConverter",
            "name": "DefinitionListConverter",
            "summary": "",
            "url": "classes/App-Console-Style-DefinitionListConverter.html"
        },                {
            "fqsen": "\\App\\Console\\Style\\DefinitionListConverter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Console-Style-DefinitionListConverter.html#method___construct"
        },                {
            "fqsen": "\\App\\Console\\Style\\DefinitionListConverter\u003A\u003Aconvert\u0028\u0029",
            "name": "convert",
            "summary": "",
            "url": "classes/App-Console-Style-DefinitionListConverter.html#method_convert"
        },                {
            "fqsen": "\\App\\Console\\Style\\DefinitionListConverter\u003A\u003Aflatten\u0028\u0029",
            "name": "flatten",
            "summary": "",
            "url": "classes/App-Console-Style-DefinitionListConverter.html#method_flatten"
        },                {
            "fqsen": "\\App\\Console\\Style\\DefinitionListConverter\u003A\u003A\u0024normalizer",
            "name": "normalizer",
            "summary": "",
            "url": "classes/App-Console-Style-DefinitionListConverter.html#property_normalizer"
        },                {
            "fqsen": "\\App\\Console\\UserCommand",
            "name": "UserCommand",
            "summary": "",
            "url": "classes/App-Console-UserCommand.html"
        },                {
            "fqsen": "\\App\\Console\\UserCommand\u003A\u003AsetUserRepository\u0028\u0029",
            "name": "setUserRepository",
            "summary": "",
            "url": "classes/App-Console-UserCommand.html#method_setUserRepository"
        },                {
            "fqsen": "\\App\\Console\\UserCommand\u003A\u003AsetValidator\u0028\u0029",
            "name": "setValidator",
            "summary": "",
            "url": "classes/App-Console-UserCommand.html#method_setValidator"
        },                {
            "fqsen": "\\App\\Console\\UserCommand\u003A\u003AvalidateDiscordId\u0028\u0029",
            "name": "validateDiscordId",
            "summary": "",
            "url": "classes/App-Console-UserCommand.html#method_validateDiscordId"
        },                {
            "fqsen": "\\App\\Console\\UserCommand\u003A\u003AARGUMENT_NAME_DISCORD_ID",
            "name": "ARGUMENT_NAME_DISCORD_ID",
            "summary": "",
            "url": "classes/App-Console-UserCommand.html#constant_ARGUMENT_NAME_DISCORD_ID"
        },                {
            "fqsen": "\\App\\Console\\UserCommand\u003A\u003AARGUMENT_DESCRIPTION_DISCORD_ID",
            "name": "ARGUMENT_DESCRIPTION_DISCORD_ID",
            "summary": "",
            "url": "classes/App-Console-UserCommand.html#constant_ARGUMENT_DESCRIPTION_DISCORD_ID"
        },                {
            "fqsen": "\\App\\Console\\UserCommand\u003A\u003A\u0024userRepository",
            "name": "userRepository",
            "summary": "",
            "url": "classes/App-Console-UserCommand.html#property_userRepository"
        },                {
            "fqsen": "\\App\\Console\\UserCommand\u003A\u003A\u0024validator",
            "name": "validator",
            "summary": "",
            "url": "classes/App-Console-UserCommand.html#property_validator"
        },                {
            "fqsen": "\\App\\Entity\\Guild",
            "name": "Guild",
            "summary": "",
            "url": "classes/App-Entity-Guild.html"
        },                {
            "fqsen": "\\App\\Entity\\Guild\u003A\u003AgetInstalled\u0028\u0029",
            "name": "getInstalled",
            "summary": "",
            "url": "classes/App-Entity-Guild.html#method_getInstalled"
        },                {
            "fqsen": "\\App\\Entity\\Guild\u003A\u003AsetInstalled\u0028\u0029",
            "name": "setInstalled",
            "summary": "",
            "url": "classes/App-Entity-Guild.html#method_setInstalled"
        },                {
            "fqsen": "\\App\\Entity\\Guild\u003A\u003A\u0024installed",
            "name": "installed",
            "summary": "",
            "url": "classes/App-Entity-Guild.html#property_installed"
        },                {
            "fqsen": "\\App\\Entity\\Traits\\DiscordIdentifiable",
            "name": "DiscordIdentifiable",
            "summary": "",
            "url": "classes/App-Entity-Traits-DiscordIdentifiable.html"
        },                {
            "fqsen": "\\App\\Entity\\Traits\\DiscordIdentifiable\u003A\u003AgetDiscordId\u0028\u0029",
            "name": "getDiscordId",
            "summary": "",
            "url": "classes/App-Entity-Traits-DiscordIdentifiable.html#method_getDiscordId"
        },                {
            "fqsen": "\\App\\Entity\\Traits\\DiscordIdentifiable\u003A\u003AsetDiscordId\u0028\u0029",
            "name": "setDiscordId",
            "summary": "",
            "url": "classes/App-Entity-Traits-DiscordIdentifiable.html#method_setDiscordId"
        },                {
            "fqsen": "\\App\\Entity\\Traits\\DiscordIdentifiable\u003A\u003A\u0024discordId",
            "name": "discordId",
            "summary": "",
            "url": "classes/App-Entity-Traits-DiscordIdentifiable.html#property_discordId"
        },                {
            "fqsen": "\\App\\Entity\\Traits\\Identifiable",
            "name": "Identifiable",
            "summary": "",
            "url": "classes/App-Entity-Traits-Identifiable.html"
        },                {
            "fqsen": "\\App\\Entity\\Traits\\Identifiable\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-Traits-Identifiable.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Traits\\Identifiable\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Traits-Identifiable.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Traits\\Timestampable",
            "name": "Timestampable",
            "summary": "",
            "url": "classes/App-Entity-Traits-Timestampable.html"
        },                {
            "fqsen": "\\App\\Entity\\Traits\\Timestampable\u003A\u003AgetCreatedAt\u0028\u0029",
            "name": "getCreatedAt",
            "summary": "",
            "url": "classes/App-Entity-Traits-Timestampable.html#method_getCreatedAt"
        },                {
            "fqsen": "\\App\\Entity\\Traits\\Timestampable\u003A\u003AsetCreatedAt\u0028\u0029",
            "name": "setCreatedAt",
            "summary": "",
            "url": "classes/App-Entity-Traits-Timestampable.html#method_setCreatedAt"
        },                {
            "fqsen": "\\App\\Entity\\Traits\\Timestampable\u003A\u003AgetUpdatedAt\u0028\u0029",
            "name": "getUpdatedAt",
            "summary": "",
            "url": "classes/App-Entity-Traits-Timestampable.html#method_getUpdatedAt"
        },                {
            "fqsen": "\\App\\Entity\\Traits\\Timestampable\u003A\u003AsetUpdatedAt\u0028\u0029",
            "name": "setUpdatedAt",
            "summary": "",
            "url": "classes/App-Entity-Traits-Timestampable.html#method_setUpdatedAt"
        },                {
            "fqsen": "\\App\\Entity\\Traits\\Timestampable\u003A\u003A\u0024createdAt",
            "name": "createdAt",
            "summary": "",
            "url": "classes/App-Entity-Traits-Timestampable.html#property_createdAt"
        },                {
            "fqsen": "\\App\\Entity\\Traits\\Timestampable\u003A\u003A\u0024updatedAt",
            "name": "updatedAt",
            "summary": "",
            "url": "classes/App-Entity-Traits-Timestampable.html#property_updatedAt"
        },                {
            "fqsen": "\\App\\Entity\\User",
            "name": "User",
            "summary": "",
            "url": "classes/App-Entity-User.html"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetRoles\u0028\u0029",
            "name": "getRoles",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getRoles"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetRoles\u0028\u0029",
            "name": "setRoles",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_setRoles"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetUserIdentifier\u0028\u0029",
            "name": "getUserIdentifier",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getUserIdentifier"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AeraseCredentials\u0028\u0029",
            "name": "eraseCredentials",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_eraseCredentials"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AROLE_USER",
            "name": "ROLE_USER",
            "summary": "",
            "url": "classes/App-Entity-User.html#constant_ROLE_USER"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AROLE_SUPER_ADMIN",
            "name": "ROLE_SUPER_ADMIN",
            "summary": "",
            "url": "classes/App-Entity-User.html#constant_ROLE_SUPER_ADMIN"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024roles",
            "name": "roles",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_roles"
        },                {
            "fqsen": "\\App\\Kernel",
            "name": "Kernel",
            "summary": "",
            "url": "classes/App-Kernel.html"
        },                {
            "fqsen": "\\App\\Repository\\GuildRepository",
            "name": "GuildRepository",
            "summary": "",
            "url": "classes/App-Repository-GuildRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\GuildRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-GuildRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\GuildRepository\u003A\u003AfindOneByDiscordId\u0028\u0029",
            "name": "findOneByDiscordId",
            "summary": "",
            "url": "classes/App-Repository-GuildRepository.html#method_findOneByDiscordId"
        },                {
            "fqsen": "\\App\\Repository\\Traits\\Alterable",
            "name": "Alterable",
            "summary": "",
            "url": "classes/App-Repository-Traits-Alterable.html"
        },                {
            "fqsen": "\\App\\Repository\\Traits\\Alterable\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "",
            "url": "classes/App-Repository-Traits-Alterable.html#method_add"
        },                {
            "fqsen": "\\App\\Repository\\Traits\\Alterable\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "",
            "url": "classes/App-Repository-Traits-Alterable.html#method_remove"
        },                {
            "fqsen": "\\App\\Repository\\UserRepository",
            "name": "UserRepository",
            "summary": "",
            "url": "classes/App-Repository-UserRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\UserRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-UserRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\UserRepository\u003A\u003AfindOneByUserIdentifier\u0028\u0029",
            "name": "findOneByUserIdentifier",
            "summary": "",
            "url": "classes/App-Repository-UserRepository.html#method_findOneByUserIdentifier"
        },                {
            "fqsen": "\\App\\Repository\\UserRepository\u003A\u003AfindOneByDiscordId\u0028\u0029",
            "name": "findOneByDiscordId",
            "summary": "",
            "url": "classes/App-Repository-UserRepository.html#method_findOneByDiscordId"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Command",
            "name": "Command",
            "summary": "",
            "url": "namespaces/app-command.html"
        },                {
            "fqsen": "\\App\\Console",
            "name": "Console",
            "summary": "",
            "url": "namespaces/app-console.html"
        },                {
            "fqsen": "\\App\\Console\\Style",
            "name": "Style",
            "summary": "",
            "url": "namespaces/app-console-style.html"
        },                {
            "fqsen": "\\App\\Entity",
            "name": "Entity",
            "summary": "",
            "url": "namespaces/app-entity.html"
        },                {
            "fqsen": "\\App\\Entity\\Traits",
            "name": "Traits",
            "summary": "",
            "url": "namespaces/app-entity-traits.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Repository",
            "name": "Repository",
            "summary": "",
            "url": "namespaces/app-repository.html"
        },                {
            "fqsen": "\\App\\Repository\\Traits",
            "name": "Traits",
            "summary": "",
            "url": "namespaces/app-repository-traits.html"
        }            ]
);
